kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: airflow-local-cluster
nodes:
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - image: kindest/node:v1.18.15
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node=worker_1"
  extraMounts:
    - hostPath: ./data
      containerPath: /tmp/data
- role: worker
  kubeadmConfigPatches:
  - image: kindest/node:v1.18.15
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node=worker_2"
  extraMounts:
    - hostPath: ./data
      containerPath: /tmp/data 
- role: worker
  kubeadmConfigPatches:
  - image: kindest/node:v1.18.15
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node=worker_3"
  extraMounts:
    - hostPath: ./data
      containerPath: /tmp/data